name: umi_celegans_analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.12.1
  - bcftools=1.22
  - umi_tools=1.1.6
  - gatk4=4.6.1.0
  - fgbio=2.5.0
  - snpeff=5.2
  - samtools=1.22.1
  - star=2.7.11b
  - multiqc=1.32
